// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvVQJapu_1PdWxj229EP8ZCOt92juq1mQ',
    appId: '1:822548013135:android:88394a122e14922b85ca3a',
    messagingSenderId: '822548013135',
    projectId: 'fintrack-2afe4',
    storageBucket: 'fintrack-2afe4.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7Y1hlLynjMyiSG91WkJ7uJFoKAjsT8xg',
    appId: '1:822548013135:ios:d2036fe03110570085ca3a',
    messagingSenderId: '822548013135',
    projectId: 'fintrack-2afe4',
    storageBucket: 'fintrack-2afe4.firebasestorage.app',
    androidClientId: '822548013135-4rvtm3apifkmlnnd0chmcup0u5ofbap4.apps.googleusercontent.com',
    iosClientId: '822548013135-cb43b4nnpl9h1k0psq5in5pqrev19bcq.apps.googleusercontent.com',
    iosBundleId: 'com.example.fintrackApp',
  );
}
